version: "3.8"
services:
  frontend:
    build:
      context: frontend
      args:
        - PORT=3000
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    networks:
      - local

  backend:    
    build:
      context: backend
      args:
        - PORT=5000
    volumes:
      - ./backend/src:/app/src
    networks:
      - local

  proxy:
    build: proxy
    restart: always
    ports:
      - 8080:80
    depends_on: 
      - frontend
      - backend
    networks:
      - local

volumes:
  db:
    driver: local

networks:
  local: {}
